use_frameworks!

target 'ChartsExplorer' do
  pod 'SwiftyJSON', git: 'https://github.com/IBM-Swift/SwiftyJSON.git'
  pod 'Charts', git: 'https://github.com/danielgindi/Charts.git', branch: 'Swift-3.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
